version: '2'
services:
  simple_crud_pbi-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/simple_crud_pbi/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=simple_crud_pbi
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
